server:
  port: 8001
  servlet:
    context-path: /files
  error:
    include-message: always
spring:
  application:
    name: file-storage-spring-boot
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
